interface FileType {
  ext: string;
  mime: string;
}

export const fileTypes: FileType[] = [
  {ext: 'acc', mime: 'audio/aac'},
  {ext: 'avi', mime: 'video/x-msvideo'},
  {ext: 'bin', mime: 'application/octet-stream'},
  {ext: 'bmp', mime: 'image/bmp'},
  {ext: 'csv', mime: 'text/csv'},
  {ext: 'dcm', mime: 'application/dicom'},
  {ext: 'dcm30', mime: 'application/dicom'},
  {ext: 'dicom', mime: 'application/dicom'},
  {ext: 'doc', mime: 'application/msword'},
  {ext: 'docx', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'},
  {ext: 'gif', mime: 'image/gif'},
  {ext: 'ico', mime: 'image/vnd.microsoft.icon'},
  {ext: 'ics', mime: 'text/calendar'},
  {ext: 'jpeg', mime: 'image/jpeg'},
  {ext: 'jpg', mime: 'image/jpeg'},
  {ext: 'mp3', mime: 'audio/mpeg'},
  {ext: 'mpeg', mime: 'video/mpeg'},
  {ext: 'opd', mime: 'application/vnd.oasis.opendocument.presentation'},
  {ext: 'ods', mime: 'application/vnd.oasis.opendocument.spreadsheet'},
  {ext: 'odt', mime: 'application/vnd.oasis.opendocument.text'},
  {ext: 'oga', mime: 'audio/ogg'},
  {ext: 'ogv', mime: 'video/ogg'},
  {ext: 'ogx', mime: 'application/ogg'},
  {ext: 'png', mime: 'image/png'},
  {ext: 'pdf', mime: 'application/pdf'},
  {ext: 'ppt', mime: 'application/vnd.ms-powerpoint'},
  {ext: 'pptx', mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation'},
  {ext: 'tif', mime: 'image/tiff'},
  {ext: 'tiff', mime: 'image/tiff'},
  {ext: 'ts', mime: 'video/mp2t'},
  {ext: 'txt', mime: 'text/plain'},
  {ext: 'vsd', mime: 'application/vnd.visio'},
  {ext: 'wav', mime: 'audio/wav'},
  {ext: 'weba', mime: 'audio/webm'},
  {ext: 'webm', mime: 'video/webm'},
  {ext: 'webp', mime: 'image/webp'},
  {ext: 'xls', mime: 'application/vnd.ms-excel'},
  {ext: 'xlsx', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},
  {ext: 'zip', mime: 'application/zip'},
];
